name: CI Checks

on: [pull_request]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Install LAPACK and BLAS
      run: |
        sudo apt-get update
        sudo apt-get install -y liblapack-dev libblas-dev
    - name: Check LAPACK and BLAS
      run: |
        ls -l /usr/lib/x86_64-linux-gnu/
  autoformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run black to test code linting
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          jupyter: true
      - name: Run isort to organize imports
        uses: isort/isort-action@master
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'
    - name: Install dependencies
      run: |
        pip install -e ".[develop]"
    - name: Lint
      run: |
        pytest . --pylint -m pylint --pylint-rcfile=.pylintrc
  static-type-checking:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'
    - name: Install dependencies
      run: |
        pip install -e ".[develop]"
    - name: Mypy
      run: |
        mypy .
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'
    - name: Install dependencies
      run: |
        pip install -e ".[develop]"
    - name: Pytest
      run: |
        pytest tests/
